services:
  web-archon:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: urbanscratcher/web-archon:latest
    ports:
      - "3001:3000"
    volumes:
      - ./.env:/usr/src/app/.env
