/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  env: {
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_TOPICS_ENDPOINT: process.env.NEXT_PUBLIC_TOPICS_ENDPOINT,
    NEXT_PUBLIC_USERS_ENDPOINT: process.env.NEXT_PUBLIC_USERS_ENDPOINT,
    NEXT_PUBLIC_COVERS_ENDPOINT: process.env.NEXT_PUBLIC_COVERS_ENDPOINT,
    NEXT_PUBLIC_COVERS_HEADLINE_ENDPOINT:
      process.env.NEXT_PUBLIC_COVERS_HEADLINE_ENDPOINT,
    NEXT_PUBLIC_INSIGHTS_ENDPOINT: process.env.NEXT_PUBLIC_INSIGHTS_ENDPOINT,
    NEXT_PUBLIC_RANDOM_INSIGHTS_ENDPOINT:
      process.env.NEXT_PUBLIC_RANDOM_INSIGHTS_ENDPOINT,
    NEXT_PUBLIC_TRENDING_INSIGHTS_ENDPOINT:
      process.env.NEXT_PUBLIC_TRENDING_INSIGHTS_ENDPOINT,
    NEXT_PUBLIC_TRENDING_AUTHORS_ENDPOINT:
      process.env.NEXT_PUBLIC_TRENDING_AUTHORS_ENDPOINT,
    NEXT_PUBLIC_HOST: process.env.NEXT_PUBLIC_HOST,
  },
  images: {
    formats: ["image/webp"],
    minimumCacheTTL: 60,
    remotePatterns: [{ hostname: "*" }],
  },
};

export default nextConfig;
